# Generated by Django 4.2.1 on 2023-05-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='../static/assets/img/default_avatar.png', upload_to='midia/users/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
