# Generated by Django 4.2.1 on 2023-05-15 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateTimeField(verbose_name='Дата начала')),
                ('date_finish', models.DateTimeField(verbose_name='Срок сдачи')),
                ('executor', models.ManyToManyField(related_name='executer_task', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель задачи')),
                ('owner', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Постановщик')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
