# Generated by Django 4.2.1 on 2023-05-29 16:08

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ru City name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='En City name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ru Country name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='En Country name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='hotels/features/icons/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['title_en'],
            },
        ),
        migrations.CreateModel(
            name='FeaturesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='name_ru')),
                ('name_en', models.CharField(max_length=100, verbose_name='name_en')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ru Name')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='En Name')),
                ('top_photo', models.ImageField(blank=True, null=True, upload_to='objects/photo/%Y/%m/%d/')),
                ('text_ru', models.TextField(blank=True, default='', null=True, verbose_name='Ru Text')),
                ('text_en', models.TextField(blank=True, default='', null=True, verbose_name='En Text')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name_en')),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('coordinates_x', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('coordinates_y', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bad_coordinates_x', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bad_coordinates_y', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('price_ru', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_en', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Objects',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='ObjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='objects/object_photos/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(blank=True, default='', verbose_name='check_in')),
                ('check_out', models.DateField(blank=True, default='', verbose_name='check_out')),
                ('guest_last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='guest_last_nam')),
                ('guest_first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='guest_first_name')),
                ('guest_patronymic', models.CharField(blank=True, default='', max_length=255, verbose_name='guest_patronymic')),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='guest_email')),
                ('guest_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='guest_phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='Reservation/Documents/%Y/%m/%d/', verbose_name='document')),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('type', models.CharField(blank=True, choices=[('RO', 'Reservation'), ('RC', 'Consultation')], default='', max_length=255)),
                ('status_pay', models.CharField(blank=True, choices=[('PD', 'Paid'), ('PP', 'Paid in part'), ('NP', 'Not paid')], default='NP', max_length=255, verbose_name='Payment State')),
                ('status_documents', models.CharField(blank=True, choices=[('ST', 'Sent'), ('NS', 'Non sent')], default='NS', max_length=255, verbose_name='Document Status')),
                ('status_order', models.BooleanField(blank=True, default=False, verbose_name='Success')),
                ('status_closed', models.BooleanField(blank=True, default=False, verbose_name='Closed')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
