# Generated by Django 4.2.1 on 2023-05-25 09:00

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ru City name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='En City name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'ordering': ['title_en'], 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ['name_en'], 'verbose_name': 'Object', 'verbose_name_plural': 'Objects'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.RenameField(
            model_name='object',
            old_name='city',
            new_name='bad_ccordinates',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='country',
            new_name='ccordinates',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='price',
            new_name='price_en',
        ),
        migrations.RemoveField(
            model_name='features',
            name='title',
        ),
        migrations.RemoveField(
            model_name='object',
            name='features',
        ),
        migrations.RemoveField(
            model_name='object',
            name='name',
        ),
        migrations.RemoveField(
            model_name='object',
            name='text',
        ),
        migrations.AddField(
            model_name='features',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='features',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='object',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='object',
            name='features_en',
            field=models.ManyToManyField(blank=True, related_name='hotels_en', related_query_name='hotel_en', to='objects.features', verbose_name='En Options'),
        ),
        migrations.AddField(
            model_name='object',
            name='features_ru',
            field=models.ManyToManyField(blank=True, related_name='hotels_ru', related_query_name='hotel_ru', to='objects.features', verbose_name='Ru Options'),
        ),
        migrations.AddField(
            model_name='object',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='En Name'),
        ),
        migrations.AddField(
            model_name='object',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ru Name'),
        ),
        migrations.AddField(
            model_name='object',
            name='price_ru',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='text_en',
            field=models.TextField(default='', verbose_name='En Text'),
        ),
        migrations.AddField(
            model_name='object',
            name='text_ru',
            field=models.TextField(default='', verbose_name='Ru Text'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Reservation/Documents/%Y/%m/%d/', verbose_name='document'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='manager',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_manager', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status_closed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Closed'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status_documents',
            field=models.CharField(blank=True, choices=[('ST', 'Sent'), ('NS', 'Non sent')], default='NS', max_length=255, verbose_name='Document Status'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status_order',
            field=models.BooleanField(blank=True, default=False, verbose_name='Success'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('PD', 'Paid'), ('PP', 'Paid in part'), ('NP', 'Not paid')], default='NP', max_length=255, verbose_name='Payment State'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.CharField(blank=True, choices=[('RO', 'Reservation'), ('RC', 'Consultation')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='features',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/features/icons/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='object',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='objects/photo/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='object',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name_en'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(blank=True, default='', verbose_name='check_in'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(blank=True, default='', verbose_name='check_out'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='guest_email'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_first_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='guest_first_name'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_last_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='guest_last_nam'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_patronymic',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='guest_patronymic'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='guest_phone'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='object',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='objects.object', verbose_name='Object Reservation'),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ru Country name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='En Country name')),
                ('city_en', models.ManyToManyField(blank=True, null=True, related_name='county_city_en', to='objects.city', verbose_name='En Countries')),
                ('city_ru', models.ManyToManyField(blank=True, null=True, related_name='county_city_ru', to='objects.city', verbose_name='Ru Countries')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AddField(
            model_name='object',
            name='city_en',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_en', to='objects.city'),
        ),
        migrations.AddField(
            model_name='object',
            name='city_ru',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_ru', to='objects.city'),
        ),
        migrations.AddField(
            model_name='object',
            name='country_en',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_en', to='objects.country'),
        ),
        migrations.AddField(
            model_name='object',
            name='country_ru',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_ru', to='objects.country'),
        ),
    ]
