# Generated by Django 4.2.1 on 2023-05-15 04:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_city_alter_object_photo_country_alter_object_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='photo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], max_length=255, verbose_name='Фото'),
        ),
    ]
