# Generated by Django 4.2.1 on 2023-05-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_city_alter_features_options_alter_object_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='bad_ccordinates',
            new_name='bad_coordinates',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='ccordinates',
            new_name='coordinates',
        ),
    ]
