# Generated by Django 4.2.1 on 2023-05-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='objectphoto',
            name='object',
        ),
        migrations.AddField(
            model_name='object',
            name='photos',
            field=models.ManyToManyField(related_name='Photos', to='objects.objectphoto', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='object',
            name='features_en',
            field=models.ManyToManyField(related_name='hotels_en', related_query_name='hotel_en', to='objects.features', verbose_name='En Options'),
        ),
        migrations.AlterField(
            model_name='object',
            name='features_ru',
            field=models.ManyToManyField(related_name='hotels_ru', related_query_name='hotel_ru', to='objects.features', verbose_name='Ru Options'),
        ),
    ]
