# Generated by Django 4.2.1 on 2023-06-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='photo',
            new_name='photos',
        ),
        migrations.RemoveField(
            model_name='objectphoto',
            name='object',
        ),
    ]
