# Generated by Django 4.2.1 on 2023-06-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_rename_photo_object_photos_remove_objectphoto_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='En Name'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ru Name'),
        ),
        migrations.AlterField(
            model_name='object',
            name='top_photo',
            field=models.ImageField(null=True, upload_to='objects/photo/%Y/%m/%d/'),
        ),
    ]
