# Generated by Django 4.2.1 on 2023-05-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_rename_bad_ccordinates_object_bad_coordinates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='bad_coordinates',
            new_name='bad_ccordinates',
        ),
    ]
