# Generated by Django 4.2.1 on 2023-06-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_remove_object_photo_remove_objectphoto_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='features_en',
            field=models.ManyToManyField(blank=True, related_name='hotels_en', related_query_name='hotel_en', to='objects.features', verbose_name='En Options'),
        ),
        migrations.AlterField(
            model_name='object',
            name='features_ru',
            field=models.ManyToManyField(blank=True, related_name='hotels_ru', related_query_name='hotel_ru', to='objects.features', verbose_name='Ru Options'),
        ),
        migrations.AlterField(
            model_name='object',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='Photos', to='objects.objectphoto', verbose_name='Photos'),
        ),
    ]
