# Generated by Django 4.2.1 on 2023-05-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_image_alter_object_photo_objectphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectphoto',
            name='photo',
            field=models.FileField(upload_to='objects/photo/', verbose_name='Фото'),
        ),
    ]
