# Generated by Django 4.2.1 on 2023-05-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_remove_object_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='object',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to='objects/photo/', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='ObjectPhoto',
        ),
    ]
