# Generated by Django 4.2.1 on 2023-05-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_delete_image_object_photos_delete_objectphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='photos',
            new_name='photo',
        ),
    ]
