# Generated by Django 4.2.1 on 2023-05-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_alter_objectphoto_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='bad_ccordinates',
            new_name='bad_coordinates_x',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='coordinates',
            new_name='bad_coordinates_y',
        ),
        migrations.AddField(
            model_name='object',
            name='coordinates_x',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='coordinates_y',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
