# Generated by Django 4.2.1 on 2023-05-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_rename_photos_object_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='objects/photo/', verbose_name='Фото'),
        ),
    ]
