# Generated by Django 4.2.1 on 2023-05-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_rename_bad_ccordinates_object_bad_coordinates_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='name_ru')),
                ('name_en', models.CharField(max_length=100, verbose_name='name_en')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='features',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.featurescategory', verbose_name='Category'),
        ),
    ]
