# Generated by Django 4.2.1 on 2023-05-16 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0009_alter_object_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='manager',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='order_manager', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status_documents',
            field=models.CharField(choices=[('ST', 'Отправлены'), ('NS', 'Не отправлены')], default='NS', max_length=255, verbose_name='Статус документов'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status_order',
            field=models.BooleanField(default=True, verbose_name='Статус сделки'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status_pay',
            field=models.CharField(choices=[('PD', 'Оплачен'), ('PP', 'Оплачен частично'), ('NP', 'Не оплачен')], default='NP', max_length=255, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='objects.object', verbose_name='Объект бронирования'),
        ),
    ]
