# Generated by Django 4.2.1 on 2023-05-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_alter_reservation_status_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('RO', 'Бронирование'), ('RC', 'Консультирование')], default='', max_length=255),
        ),
    ]
