# Generated by Django 4.2.1 on 2023-05-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_reservation_document_alter_reservation_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
