# Generated by Django 4.2.1 on 2023-05-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0018_alter_reservation_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыта'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status_order',
            field=models.BooleanField(default=False, verbose_name='Обработана'),
        ),
    ]
