# Generated by Django 4.2.1 on 2023-05-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0020_alter_reservation_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status_closed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Закрыта'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status_documents',
            field=models.CharField(blank=True, choices=[('ST', 'Отправлены'), ('NS', 'Не отправлены')], default='NS', max_length=255, verbose_name='Статус документов'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status_order',
            field=models.BooleanField(blank=True, default=False, verbose_name='Обработана'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('PD', 'Оплачен'), ('PP', 'Оплачен частично'), ('NP', 'Не оплачен')], default='NP', max_length=255, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type',
            field=models.CharField(blank=True, choices=[('RO', 'Бронирование'), ('RC', 'Консультирование')], default='', max_length=255),
        ),
    ]
