# Generated by Django 4.2.1 on 2023-05-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='order',
            new_name='reservation',
        ),
    ]
