# Generated by Django 4.2.1 on 2023-05-29 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatss', to='objects.reservation'),
        ),
    ]
