# Generated by Django 4.2.1 on 2023-06-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Messege', 'verbose_name_plural': 'Messeges'},
        ),
    ]
