# Generated by Django 4.2.1 on 2023-05-16 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0009_alter_object_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status_pay', models.CharField(choices=[('PD', 'Оплачен'), ('PP', 'Оплачен частично'), ('NP', 'Не оплачен')], default='NP', max_length=255, verbose_name='Статус оплаты')),
                ('status_documents', models.CharField(choices=[('ST', 'Отправлены'), ('NS', 'Не отправлены')], default='NS', max_length=255, verbose_name='Статус документов')),
                ('status_order', models.BooleanField(default=True, verbose_name='Статус сделки')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_manager', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object', verbose_name='Объект бронирования')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
